version: '1.0'
stages:
  - checkout
  - package
  - test
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
    git: github
  labelinteractive_image:
    title: Building Label Interactive Docker Image
    type: build
    stage: package
    image_name: labelinteractive
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: ./development/Dockerfile
  javascript_tests_image:
    title: Building Javascript Test Docker Image
    type: build
    stage: package
    image_name: javascripttests
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}-javascript
    dockerfile: ./testing/Dockerfile.node
  unit_test:
    title: Running Python Unit tests
    image: '${{labelinteractive_image}}'
    stage: test
    commands:
      - make linttest
  unit_test_javascript:
    title: Running Javascript Unit tests
    image: '${{javascript_tests_image}}'
    stage: test
    commands:
      - npm install && npm run lint-test
  deploy_to_Balena:
    title: Deploying repository to Balena
    image: acmilabs/balena-cli:arm
    stage: deploy
    commands:
      - bash /code/add-key.sh github.com $GITHUB_FINGERPRINT
      - echo "$SSH_KEY" | awk '{gsub(/\\n/,"\n")}1' >> keyfile
      - chmod 600 keyfile
      - ssh-agent bash -c 'ssh-add -k keyfile; git clone git@github.com:${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}.git'
      - cd ${{CF_REPO_NAME}}
      - git checkout ${{CF_BRANCH}}
      - balena login --token $BALENA_TOKEN
      - balena push s__interactive-label-tap-pi-4
    when:
      branch:
        only:
          - master
