version: "3"

services:
  javascripttests:
    build:
      context: "../"
      dockerfile: testing/Dockerfile.node
      args:
        IS_LOCAL_ENV: "true"
    hostname: javascripttests
    container_name: javascripttests
    volumes:
      - ../:/code
    ports:
      - "9229:9229"
    command: ./scripts/test.sh
